language: cpp

sudo: required
dist: trusty

branches:
    only:
        - master
        - development
        - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

matrix:
    include:
        - os: linux
          env: QT_BASE=48 COMPILER=g++-4.6 CMAKE_BUILD_TYPE=Debug

        - os: linux
          env: QT_BASE=48 COMPILER=clang++

        - os: linux
          env: QT_BASE=592 COMPILER=g++-4.8 CMAKE_BUILD_TYPE=RelWithDebInfo

        - os: linux
          env: QT_BASE=592 COMPILER=clang++ CMAKE_BUILD_TYPE=Debug

        - os: osx
          env: CMAKE_BUILD_TYPE=RelWithDebInfo
          compiler: clang

install:
    - |
      if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
        wget http://www.cmake.org/files/v3.2/cmake-3.2.0-Linux-x86_64.tar.gz &&
        tar -xzf cmake-3.2.0-Linux-x86_64.tar.gz &&
        sudo cp -fR cmake-3.2.0-Linux-x86_64/* /usr &&
        sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test &&
        if [ "${QT_BASE}" = "592" ]; then
          sudo apt-add-repository -y ppa:beineri/opt-qt592-trusty &&
          sudo apt-get -qq update &&
          sudo apt-get -qq install qt59tools qt59base qt59webchannel qt59webengine qt59websockets &&
          if [ "${COMPILER}" = "clang++" ]; then
            export CXX="clang++" &&
            export CC="clang"
          fi
        else
          export DISPLAY=:99.0 &&
          sh -e /etc/init.d/xvfb start &&
          sudo apt-get -qq update &&
          if [ "${COMPILER}" = "g++-4.6" ]; then
            sudo apt-get -qq install g++-4.6 gcc-4.6 &&
            export CXX="g++-4.6" &&
            export CC="gcc-4.6"
          else
            export CXX="clang++" &&
            export CC="clang"
          fi
        fi
      else
        brew update &&
        brew unlink cmake &&
        brew install cmake &&
        brew link cmake &&
        brew install qt5 &&
        chmod -R 755 /usr/local/opt/qt5/*
      fi

before_script:
    - export QEVERCLOUD_DIR=$(pwd)
    - mkdir build
    - cd build
    - cmake --version
    - |
      if [ "${QT_BASE}" = "592" ]; then
        source /opt/qt59/bin/qt59-env.sh &&
        cmake -DUSE_QT5=1 -DCMAKE_INSTALL_PREFIX=$(pwd)/installdir ..
      elif [ "${TRAVIS_OS_NAME}" = "osx" ]; then
        cmake -DCMAKE_PREFIX_PATH=/usr/local/opt/qt5/lib/cmake -DUSE_QT5=1 -DCMAKE_INSTALL_PREFIX=$(pwd)/installdir ..
      else
        cmake -DCMAKE_INSTALL_PREFIX=$(pwd)/installdir ..
      fi

script:
    - make
    - make check
    - make install

after_success:
    - |
      if [ "${TRAVIS_OS_NAME}" = "linux" ] && [ "${QT_BASE}" = "592" ] && [ "${COMPILER}" = "g++-4.8" ]; then
        if [ "${TRAVIS_BRANCH}" = "master" ] || [ "${TRAVIS_BRANCH}" = "development" ]; then
          cd $QEVERCLOUD_DIR/build/installdir &&
          7z a qevercloud_linux_qt_${QT_BASE}_x86_64.zip * &&
          wget https://github.com/d1vanov/ciuploadtool/releases/download/continuous-master/ciuploadtool_linux.zip &&
          unzip ciuploadtool_linux.zip &&
          chmod 755 ciuploadtool &&
          ./ciuploadtool -suffix="$TRAVIS_BRANCH" qevercloud_linux_qt_${QT_BASE}_x86_64.zip
        fi
      elif [ "${TRAVIS_OS_NAME}" = "osx" ]; then
        if [ "${TRAVIS_BRANCH}" = "master" ] || [ "${TRAVIS_BRANCH}" = "development" ]; then
          cd $QEVERCLOUD_DIR/build/installdir &&
          7z a qevercloud_mac_x86_64.zip * &&
          wget https://github.com/d1vanov/ciuploadtool/releases/download/continuous-master/ciuploadtool_mac.zip &&
          unzip ciuploadtool_mac.zip &&
          chmod 755 ciuploadtool &&
          ./ciuploadtool -suffix="$TRAVIS_BRANCH" qevercloud_mac_x86_64.zip
        fi
      fi
