if(_QEVERCLOUD_USE_QT6)
  if(NOT DEFINED OpenGL_GL_PREFERENCE AND NOT CACHE{OpenGL_GL_PREFERENCE} AND NOT ENV{OpenGL_GL_PREFERENCE})
    set(OpenGL_GL_PREFERENCE GLVND)
  endif()
  find_package(Qt6 6.0.0 COMPONENTS Core Gui Network ${QEVERCLOUD_FIND_QT_ARGS})
elseif(QEVERCLOUD_HAS_OAUTH)
  if(QEVERCLOUD_USE_QT_WEB_ENGINE)
    find_package(Qt5 5.9.5 COMPONENTS Core Widgets Network WebEngineCore WebEngineWidgets ${QEVERCLOUD_FIND_QT_ARGS})
  else()
    find_package(Qt5 5.9.5 COMPONENTS Core Widgets Network WebKit WebKitWidgets ${QEVERCLOUD_FIND_QT_ARGS})
  endif()
else()
  find_package(Qt5 5.9.5 COMPONENTS Core Network ${QEVERCLOUD_FIND_QT_ARGS})
endif()
